Repository Badgerati/Pode, pull requests merged in 2018-06, with the labels that each got.

#28 https example
  examples/web-pages-https.ps1
Labels: documentation

#29 Issue 22 - Fix for High CPU and Terminating
  README.md
  examples/loop-server.ps1
  examples/public/scripts/simple.js
  examples/public/scripts/simple.js.pode
  examples/views/simple.pode
  src/Tools/Helpers.ps1
  src/Tools/Server.ps1
  src/Tools/Session.ps1
  src/Tools/SmtpServer.ps1
  src/Tools/TcpServer.ps1
  src/Tools/WebServer.ps1
Labels: bug, enhancement

#34 Resolves #32: Add support to only listen on a specific IP address
  README.md
  examples/web-pages.ps1
  src/Tools/Helpers.ps1
  src/Tools/Server.ps1
  src/Tools/Session.ps1
  src/Tools/SmtpServer.ps1
  src/Tools/TcpServer.ps1
  src/Tools/WebServer.ps1
Labels: enhancement

#47 0.13.0
  .gitignore
  README.md
  examples/logging.ps1
  examples/shared-state.ps1
  examples/web-pages.ps1
  packers/choco/pode.nuspec
  src/Pode.psd1
  src/Tools/Helpers.ps1
  src/Tools/Logging.ps1
  src/Tools/Responses.ps1
  src/Tools/Server.ps1
  src/Tools/Session.ps1
  src/Tools/SmtpServer.ps1
  src/Tools/TcpServer.ps1
  src/Tools/Timers.ps1
  src/Tools/WebServer.ps1
Labels: new-release
