Repository Badgerati/Pode, pull requests merged in 2019-10, with the labels that each got.

#388 Add -ContentType Parameter, helps #386
  src/Public/Responses.ps1
Labels: enhancement :arrow_up:

#393 #389: Adds new functions to allow adding of custom body parsers
  docs/Tutorials/Middleware/Types/BodyParsing.md
  src/Private/Context.ps1
  src/Private/Helpers.ps1
  src/Private/Server.ps1
  src/Public/Middleware.ps1
  tests/unit/Helpers.Tests.ps1
  tests/unit/Middleware.Tests.ps1
  tests/unit/Server.Tests.ps1
Labels: feature :sunny:

#391 State description
  src/Public/State.ps1
Labels: documentation :book:, invalid

#394 #390: Adds support for setting StatusCode on Write-Response functions
  src/Public/Responses.ps1
Labels: enhancement :arrow_up:
