Repository Badgerati/Pode, pull requests merged in 2021-04, with the labels that each got.

#727 Allow referencing component schemas in component schemas
  src/Pode.psd1
  src/Private/OpenApi.ps1
  src/Public/OpenApi.ps1
Labels: enhancement :arrow_up:

#729 Fix something, i did wrong
  src/Private/OpenApi.ps1
Labels: bug :bug:

#737 v2.2.3
  docs/release-notes.md
  packers/choco/pode.nuspec
  pode.build.ps1
Labels: new-release :package:, urgent :grey_exclamation:
