Repository Badgerati/Pode, pull requests merged in 2021-08, with the labels that each got.

#796 Text wrapping fix for ldapsearch
  src/Private/Authentication.ps1
Labels: bug :bug:

#800 Update and rename FunctionsAndModules.md to AutomaticFunctionsAndModu…
  docs/Tutorials/Routes/Utilities/AutomaticFunctionsAndModules.md
Labels: documentation :book:

#804 v2.4.1
  docs/Hosting/IIS.md
  docs/Tutorials/Authentication/Inbuilt/WindowsAD.md
  docs/Tutorials/Certificates.md
  docs/Tutorials/Routes/Utilities/AutomaticFunctionsAndModules.md
  docs/release-notes.md
  examples/certs/cert.pem
  examples/certs/cert_nodes.pem
  examples/certs/key.pem
  examples/certs/key_nodes.pem
  examples/web-pages-https.ps1
  src/Pode.psd1
  src/Private/Authentication.ps1
  src/Private/Context.ps1
  src/Private/Helpers.ps1
  src/Private/Security.ps1
  src/Public/Authentication.ps1
  src/Public/Core.ps1
  src/Public/Utilities.ps1
  tests/integration/RestApi.Https.Tests.ps1
Labels: new-release :package:
