Repository Badgerati/Pode, pull requests merged in 2022-10, with the labels that each got.

#975 Update readme sample code image to SVG
  README.md
  images/example_code_readme.svg
Labels: documentation :book:

#1023 Add links to WebEvent properties, and property definitions for request/response
  docs/Tutorials/Endware.md
  docs/Tutorials/WebEvent.md
Labels: hacktoberfest-accepted

#1025 Start of a roadmap and project board
  README.md
  docs/roadmap.md
  mkdocs.yml
Labels: hacktoberfest-accepted

#1026 v2.7.2
  .gitignore
  README.md
  docs/Tutorials/Authentication/Inbuilt/WindowsAD.md
  docs/Tutorials/Endware.md
  docs/Tutorials/WebEvent.md
  docs/release-notes.md
  docs/roadmap.md
  images/example_code_readme.svg
  mkdocs.yml
  src/Private/Authentication.ps1
  src/Private/Helpers.ps1
  src/Private/Server.ps1
  src/Public/Authentication.ps1
  src/Public/Core.ps1
  tests/unit/_.Tests.ps1
Labels: new-release :package:, hacktoberfest-accepted

#1027 Add workflows for auto-assigning projects
  .github/workflows/label-issue-project.yml
  .github/workflows/open-issue-project.yml
  README.md
  docs/roadmap.md
Labels: bau :briefcase:
