Repository Badgerati/Pode, pull requests merged in 2024-06, with the labels that each got.

#1295 Rename internal functions to be singular to align with PowerShell best practice; Add additional debug logging for some internal exceptions
  PSScriptAnalyzerSettings.psd1
  examples/timers.ps1
  pode.build.ps1
  src/Private/Authentication.ps1
  src/Private/AutoImport.ps1
  src/Private/Context.ps1
  src/Private/CronParser.ps1
  src/Private/Cryptography.ps1
  src/Private/Endpoints.ps1
  src/Private/FileMonitor.ps1
  src/Private/FileWatchers.ps1
  src/Private/Helpers.ps1
  src/Private/Logging.ps1
  src/Private/Metrics.ps1
  src/Private/Middleware.ps1
  src/Private/OpenApi.ps1
  src/Private/PodeServer.ps1
  src/Private/Routes.ps1
  src/Private/Schedules.ps1
  src/Private/ScopedVariables.ps1
  src/Private/Secrets.ps1
  src/Private/Security.ps1
  src/Private/Server.ps1
  src/Private/Serverless.ps1
  src/Private/ServiceServer.ps1
  src/Private/Setup.ps1
  src/Private/SmtpServer.ps1
  src/Private/Streams.ps1
  src/Private/TcpServer.ps1
  src/Private/Timers.ps1
  src/Private/WebSockets.ps1
  src/Public/Authentication.ps1
  src/Public/Core.ps1
  src/Public/FileWatchers.ps1
  src/Public/Flash.ps1
  src/Public/Logging.ps1
  src/Public/Metrics.ps1
  src/Public/OAComponents.ps1
  src/Public/OpenApi.ps1
  src/Public/Responses.ps1
  src/Public/Routes.ps1
  src/Public/SSE.ps1
  src/Public/Schedules.ps1
  src/Public/ScopedVariables.ps1
  src/Public/Security.ps1
  src/Public/Sessions.ps1
  src/Public/Tasks.ps1
  src/Public/Utilities.ps1
  src/Public/Verbs.ps1
  src/Public/WebSockets.ps1
  tests/unit/CronParser.Tests.ps1
  tests/unit/Cryptography.Tests.ps1
  tests/unit/Helpers.Tests.ps1
  tests/unit/Routes.Tests.ps1
  tests/unit/Schedules.Tests.ps1
  tests/unit/Server.Tests.ps1
  tests/unit/Serverless.Tests.ps1
Labels: internal-code :hammer:

#1321 Fixes a misspelled variable in Add-PodeOAExternalRoute
  examples/OpenApiTuttiFrutti.ps1
  src/Private/OpenApi.ps1
Labels: bug :bug:

#1319 Fixes the Write-Pode(*)Response functions so the Value parameter appropriately handles when an array is passed using piping
  examples/Write-Response.ps1
  src/Private/Helpers.ps1
  src/Public/Responses.ps1
  tests/unit/Helpers.Tests.ps1
  tests/unit/Responses.Tests.ps1
Labels: bug :bug:

#1328 Make preview builds optional for PR merges
  .github/workflows/ci-no-build-needed.yml
  .github/workflows/ci-pwsh_preview.yml
Labels: packaging :package:
