Repository Badgerati/Pode, pull requests merged in 2024-11, with the labels that each got.

#1440 Fixes error message appearing when using self-signed certificates on localhost
  docs/Tutorials/WebEvent.md
  examples/Web-PagesHttps.ps1
  pode.build.ps1
  src/Listener/PodeContext.cs
  src/Listener/PodeContextState.cs
  src/Listener/PodeEndpoint.cs
  src/Listener/PodeForm.cs
  src/Listener/PodeHelpers.cs
  src/Listener/PodeHttpRequest.cs
  src/Listener/PodeItemQueue.cs
  src/Listener/PodeListener.cs
  src/Listener/PodeRequest.cs
  src/Listener/PodeRequestException.cs
  src/Listener/PodeResponse.cs
  src/Listener/PodeSmtpRequest.cs
  src/Listener/PodeSocket.cs
  src/Listener/PodeStreamState.cs
  src/Private/Helpers.ps1
  src/Private/Mappers.ps1
  src/Private/PodeServer.ps1
  tests/unit/Helpers.Tests.ps1
Labels: bug :bug:

#1441 Adds v2.11.1 release notes
  docs/release-notes.md
Labels: internal-code :hammer:

#1444 Adds VirusTotal package scanning Action
  .github/workflows/VirusTotal-Releases.yml
  .github/workflows/VirusTotal.yml
  pode.build.ps1
Labels: security :lock:

#1446 Change VT scan to daily, and only on pushes to develop, and PRs to master
  .github/workflows/VirusTotal.yml
  .vscode/settings.json
Labels: internal-code :hammer:

#1448 Update PowerShell to 7.2.24 for CI environment due to unavailability of 7.2.19
  .github/workflows/ci-pwsh7_2.yml
Labels: packaging :package:

#1454 Fix OpenAPI Route Parameter Handling in Pode
  src/Public/Routes.ps1
  tests/integration/specs/OpenApi-TuttiFrutti_3.0.3.json
  tests/integration/specs/OpenApi-TuttiFrutti_3.1.0.json
Labels: bug :bug:

#1457 Remove PS7.2 and .NET6 support, as they're EOL now; Bump Alpine version in Docker image to v3.20
  .github/workflows/VirusTotal-Releases.yml
  .github/workflows/VirusTotal.yml
  .github/workflows/ci-pwsh7_2.yml
  alpine.dockerfile
  pode.build.ps1
  src/Listener/Pode.csproj
Labels: packaging :package:

#1458 Quick VirusTotal Fix for .NET9
  .github/workflows/VirusTotal.yml
Labels: internal-code :hammer:
