Repository Badgerati/Pode, pull requests merged in 2024-09, with the labels that each got.

#1373 Dynamically load the Pode DLL relevant to the version of PowerShell
  pode.build.ps1
  src/Pode.psm1
Labels: enhancement :arrow_up:

#1393 Improves Error Handling in Schedules, Timers, Tasks, and Logging; Removes Global scope from TimerEvent; Adds functions for retrieving Schedule and Task Processes
  docs/Tutorials/Schedules.md
  docs/Tutorials/Tasks.md
  examples/Web-PagesKestrel.ps1
  pode.build.ps1
  src/Locales/ar/Pode.psd1
  src/Locales/de/Pode.psd1
  src/Locales/en-us/Pode.psd1
  src/Locales/en/Pode.psd1
  src/Locales/es/Pode.psd1
  src/Locales/fr/Pode.psd1
  src/Locales/it/Pode.psd1
  src/Locales/ja/Pode.psd1
  src/Locales/ko/Pode.psd1
  src/Locales/nl/Pode.psd1
  src/Locales/pl/Pode.psd1
  src/Locales/pt/Pode.psd1
  src/Locales/zh/Pode.psd1
  src/Pode.psd1
  src/Private/Context.ps1
  src/Private/Helpers.ps1
  src/Private/Logging.ps1
  src/Private/Schedules.ps1
  src/Private/Server.ps1
  src/Private/Tasks.ps1
  src/Private/Timers.ps1
  src/Public/Schedules.ps1
  src/Public/Tasks.ps1
  src/Public/Timers.ps1
  src/Public/Utilities.ps1
  tests/unit/Helpers.Tests.ps1
  tests/unit/Server.Tests.ps1
  tests/unit/_.Tests.ps1
Labels: enhancement :arrow_up:

#1384 Customizing and Managing Runspace Names
  PSScriptAnalyzerSettings.psd1
  docs/Getting-Started/Debug.md
  examples/Schedules.ps1
  src/Pode.psd1
  src/Private/FileWatchers.ps1
  src/Private/Gui.ps1
  src/Private/Helpers.ps1
  src/Private/Logging.ps1
  src/Private/PodeServer.ps1
  src/Private/Runspaces.ps1
  src/Private/Schedules.ps1
  src/Private/ServiceServer.ps1
  src/Private/SmtpServer.ps1
  src/Private/Tasks.ps1
  src/Private/TcpServer.ps1
  src/Private/Timers.ps1
  src/Private/WebSockets.ps1
  src/Public/Core.ps1
  src/Public/Runspaces.ps1
  src/Public/Schedules.ps1
  src/Public/Tasks.ps1
  src/Public/Timers.ps1
  src/Public/Utilities.ps1
  tests/integration/Schedules.Tests.ps1
  tests/unit/Schedules.Tests.ps1
  tests/unit/Timers.Tests.ps1
Labels: enhancement :arrow_up:

#1398 Update Schedules.Tests.ps1
  tests/integration/Schedules.Tests.ps1
Labels: internal-code :hammer:

#1397 Fixes retrieving DNS domain name on macOS
  src/Private/Authentication.ps1
Labels: bug :bug:

#1399 Replaces occurrences of New-Object with new()
  .github/CONTRIBUTING.md
  .github/workflows/PSScriptAnalyzer.yml
  .vscode/settings.json
  PSScriptAnalyzerSettings.psd1
  analyzers/AvoidNewObjectRule.psm1
  docs/Servers/TCP.md
  docs/Tutorials/Authentication/Inbuilt/UserFile.md
  docs/Tutorials/Compression/Requests.md
  docs/Tutorials/Middleware/Types/Sessions.md
  examples/Web-Pages.ps1
  src/Locales/ar/Pode.psd1
  src/Locales/de/Pode.psd1
  src/Locales/en-us/Pode.psd1
  src/Locales/en/Pode.psd1
  src/Locales/es/Pode.psd1
  src/Locales/fr/Pode.psd1
  src/Locales/it/Pode.psd1
  src/Locales/ja/Pode.psd1
  src/Locales/ko/Pode.psd1
  src/Locales/nl/Pode.psd1
  src/Locales/pl/Pode.psd1
  src/Locales/pt/Pode.psd1
  src/Locales/zh/Pode.psd1
  src/Private/Authentication.ps1
  src/Private/Context.ps1
  src/Private/FileMonitor.ps1
  src/Private/Helpers.ps1
  src/Private/ScopedVariables.ps1
  src/Private/Server.ps1
  src/Private/Serverless.ps1
  src/Private/Sessions.ps1
  src/Private/Streams.ps1
  src/Public/Responses.ps1
  tests/integration/RestApi.Https.Tests.ps1
  tests/integration/RestApi.Tests.ps1
  tests/unit/Localization.Tests.ps1
  tests/unit/Logging.Tests.ps1
  tests/unit/Server.Tests.ps1
  tests/unit/Serverless.Tests.ps1
Labels: enhancement :arrow_up:

#1390 Fixes OpenAPI PowerShell 5.1 compatibility issue while testing schemas; Fixes OpenAPI DefinitionTag being null in some functions; Changes "-ContentMediaType" and "-MediaType" parameters to "-ContentType" on most OpenAPI functions; Ensures the generated OpenAPI document now maintains element ordering
  docs/Tutorials/OpenAPI/1Overview.md
  docs/Tutorials/OpenAPI/3Components.md
  docs/Tutorials/OpenAPI/5ParameterValidation.md
  docs/Tutorials/OpenAPI/6MultipleDefinitions.md
  docs/Tutorials/OpenAPI/Specification/v3.0.3.md
  examples/OpenApi-TuttiFrutti.ps1
  examples/PetStore/Petstore-OpenApi.ps1
  examples/PetStore/Petstore-OpenApiMultiTag.ps1
  src/Private/Helpers.ps1
  src/Private/OpenApi.ps1
  src/Public/OAComponents.ps1
  src/Public/OAProperties.ps1
  src/Public/OpenApi.ps1
  src/Public/Routes.ps1
  tests/integration/OpenApi.Tests.ps1
  tests/integration/specs/OpenApi-TuttiFrutti_3.0.3.json
  tests/integration/specs/OpenApi-TuttiFrutti_3.1.0.json
  tests/unit/OpenApi.Tests.ps1
  tests/unit/PrivateOpenApi.Tests.ps1
  tests/unit/Routes.Tests.ps1
Labels: bug :bug:

#1388 Support passing Arrays to Functions Using Piping
  PSScriptAnalyzerSettings.psd1
  src/Locales/ar/Pode.psd1
  src/Locales/de/Pode.psd1
  src/Locales/en-us/Pode.psd1
  src/Locales/en/Pode.psd1
  src/Locales/es/Pode.psd1
  src/Locales/fr/Pode.psd1
  src/Locales/it/Pode.psd1
  src/Locales/ja/Pode.psd1
  src/Locales/ko/Pode.psd1
  src/Locales/nl/Pode.psd1
  src/Locales/pl/Pode.psd1
  src/Locales/pt/Pode.psd1
  src/Locales/zh/Pode.psd1
  src/Private/Cryptography.ps1
  src/Private/Helpers.ps1
  src/Private/OpenApi.ps1
  src/Private/Responses.ps1
  src/Private/Secrets.ps1
  src/Private/Server.ps1
  src/Public/Access.ps1
  src/Public/Authentication.ps1
  src/Public/Caching.ps1
  src/Public/Core.ps1
  src/Public/Middleware.ps1
  src/Public/OAComponents.ps1
  src/Public/OAProperties.ps1
  src/Public/OpenApi.ps1
  src/Public/Responses.ps1
  src/Public/Routes.ps1
  src/Public/SSE.ps1
  src/Public/Secrets.ps1
  src/Public/State.ps1
  src/Public/Tasks.ps1
  src/Public/Threading.ps1
  src/Public/Timers.ps1
  src/Public/Utilities.ps1
  tests/unit/Helpers.Tests.ps1
  tests/unit/OpenApi.Tests.ps1
  tests/unit/Routes.Tests.ps1
  tests/unit/State.Tests.ps1
Labels: enhancement :arrow_up:

#1400 Fixes User being needlessly splatted when passed to scriptblock for some Authentication methods; Fixes session scoped variable when remapping while setting values
  examples/Web-AuthFormFile.ps1
  src/Private/Authentication.ps1
  src/Private/ScopedVariables.ps1
Labels: bug :bug:

#1401 Ignore accepted PSAnalyzer warnings
  PSScriptAnalyzerSettings.psd1
  examples/Web-Sse.ps1
  src/Private/Helpers.ps1
  src/Private/Timers.ps1
  src/Public/Access.ps1
  src/Public/Authentication.ps1
  src/Public/Events.ps1
  src/Public/FileWatchers.ps1
  src/Public/Flash.ps1
  src/Public/Handlers.ps1
  src/Public/Logging.ps1
  src/Public/OpenApi.ps1
  src/Public/Responses.ps1
  src/Public/Routes.ps1
  src/Public/Runspaces.ps1
  src/Public/SSE.ps1
  src/Public/Schedules.ps1
  src/Public/ScopedVariables.ps1
  src/Public/Security.ps1
  src/Public/State.ps1
  src/Public/Tasks.ps1
  src/Public/Threading.ps1
  src/Public/Timers.ps1
  src/Public/Utilities.ps1
  src/Public/Verbs.ps1
Labels: internal-code :hammer:

#1402 2.11.0 Prep
  docs/release-notes.md
  pode.build.ps1
Labels: internal-code :hammer:
