Repository Badgerati/Pode, pull requests merged in 2024-07, with the labels that each got.

#1347 `-AdditionalProperties` doesn't appear on the OpenAPI document despite using the `-NoAdditionalProperties` parameter.
  src/Private/OpenApi.ps1
Labels: bug :bug:

#1338 Automate Endpoint Assignment for OAViewer in Pode
  examples/OpenApiTuttiFrutti.ps1
  examples/PetStore/Petstore-openApiMultiTag.ps1
  src/Public/OpenApi.ps1
Labels: enhancement :arrow_up:

#1342 Add GitHub Codespace Configuration and Getting Started Guide for Pode
  .devcontainer/devcontainer.json
  docs/Getting-Started/GitHubCodespace.md
  examples/HelloWorld/HelloWorld.ps1
  pode.build.ps1
Labels: packaging :package:

#1340 Add configuration parameter `Web.OpenApi.UsePodeYamlInternal`
  docs/Tutorials/Configuration.md
  docs/Tutorials/Routes/Utilities/ContentTypes.md
  src/Private/Context.ps1
  src/Private/Helpers.ps1
Labels: enhancement :arrow_up:

#1352 Update MIME types to comply with RFC9512 and RFC5323
  src/Private/Helpers.ps1
  src/Private/Mappers.ps1
  src/Public/OpenApi.ps1
  src/Public/Responses.ps1
  tests/integration/RestApi.Https.Tests.ps1
  tests/unit/Mappers.Tests.ps1
  tests/unit/Middleware.Tests.ps1
  tests/unit/Responses.Tests.ps1
Labels: enhancement :arrow_up:

#1332 Adds documentation for CORS; Adds missing features to the Feature List; Updates Known Issues for PowerShell classes with PS7.4's SafeThread support; Splits OpenAPI documentation into multiple pages
  README.md
  docs/Getting-Started/FirstApp.md
  docs/Getting-Started/KnownIssues.md
  docs/Tutorials/CORS.md
  docs/Tutorials/Configuration.md
  docs/Tutorials/Endpoints/Basics.md
  docs/Tutorials/OpenAPI/1Overview.md
  docs/Tutorials/OpenAPI/2Properties.md
  docs/Tutorials/OpenAPI/3Components.md
  docs/Tutorials/OpenAPI/4DocumentationTools.md
  docs/Tutorials/OpenAPI/5ParameterValidation.md
  docs/Tutorials/OpenAPI/6MultipleDefinitions.md
  docs/Tutorials/OpenAPI/Overview.md
  docs/Tutorials/Routes/Utilities/ErrorPages.md
  docs/index.md
  src/Public/Core.ps1
  tests/unit/_.Tests.ps1
Labels: documentation :book:

#1359 Fixes the login redirect URL logic for OAuth2 flows when using -SuccessUseOrigin
  src/Listener/PodeContext.cs
  src/Private/Authentication.ps1
  src/Private/Security.ps1
  src/Public/Security.ps1
Labels: bug :bug:

#1339 Add `Rename-PodeOADefinitionTag` Function
  docs/Tutorials/OpenAPI/6MultipleDefinitions.md
  docs/Tutorials/Routes/Overview.md
  examples/server.psd1
  src/Locales/ar/Pode.psd1
  src/Locales/de/Pode.psd1
  src/Locales/en-us/Pode.psd1
  src/Locales/en/Pode.psd1
  src/Locales/es/Pode.psd1
  src/Locales/fr/Pode.psd1
  src/Locales/it/Pode.psd1
  src/Locales/ja/Pode.psd1
  src/Locales/ko/Pode.psd1
  src/Locales/pl/Pode.psd1
  src/Locales/pt/Pode.psd1
  src/Locales/zh/Pode.psd1
  src/Pode.psd1
  src/Private/Context.ps1
  src/Private/OpenApi.ps1
  src/Public/OpenApi.ps1
  tests/unit/OpenApi.Tests.ps1
  tests/unit/PrivateOpenApi.Tests.ps1
Labels: enhancement :arrow_up:

#1356 Dutch language support
  src/Locales/nl/Pode.psd1
  tests/unit/Localization.Tests.ps1
Labels: enhancement :arrow_up:

#1358 Fixes [ordered] comparisons in PowerShell 5.1; Fixes OpenAPI version validation check in PowerShell 5.1; Fixes for various OpenAPI issues
  src/Locales/ar/Pode.psd1
  src/Locales/de/Pode.psd1
  src/Locales/en-us/Pode.psd1
  src/Locales/en/Pode.psd1
  src/Locales/es/Pode.psd1
  src/Locales/fr/Pode.psd1
  src/Locales/it/Pode.psd1
  src/Locales/ja/Pode.psd1
  src/Locales/ko/Pode.psd1
  src/Locales/nl/Pode.psd1
  src/Locales/pl/Pode.psd1
  src/Locales/pt/Pode.psd1
  src/Locales/zh/Pode.psd1
  src/Private/OpenApi.ps1
  src/Private/Secrets.ps1
  src/Public/OAComponents.ps1
  src/Public/OpenApi.ps1
  src/Public/Routes.ps1
  tests/unit/OpenApi.Tests.ps1
Labels: bug :bug:
