Repository Badgerati/Pode, pull requests merged in 2024-10, with the labels that each got.

#1413 Fixes Test-PodeCacheStorage being called with incorrect -Key parameter
  src/Public/Caching.ps1
Labels: bug :bug:

#1424 Refactor Byte Conversion Functions; Remove Duplicate Task Process Definitions
  src/Private/Streams.ps1
  src/Public/Responses.ps1
  src/Public/Tasks.ps1
Labels: bug :bug:

#1423 Fix OpenAPI Route Path Conversion for Placeholder Unescaping and Relocate Function (#1422)
  examples/OpenApi-SimplePotato.ps1
  src/Private/OpenApi.ps1
  src/Private/Routes.ps1
  src/Public/OpenApi.ps1
  src/Public/Routes.ps1
  tests/unit/PrivateOpenApi.Tests.ps1
Labels: bug :bug:

#1404 Add Pester Test to Check for Duplicate Function Definitions
  tests/unit/_.Tests.ps1
Labels: packaging :package:

#1407 `Initialize-PodeOpenApiTable` fails to initialize OpenAPI table when `DefaultDefinitionTag` param is Null
  examples/Web-AuthBasic.ps1
  examples/Web-UsePodeAuth.ps1
  examples/auth/SampleAuth.ps1
  src/Private/OpenApi.ps1
  tests/unit/_.Tests.ps1
Labels: bug :bug:

#1418 Fix for ConvertTo-PodeYaml failing, when passed object contains a Key named "Count"
  src/Private/Helpers.ps1
  tests/unit/Helpers.Tests.ps1
Labels: bug :bug:

#1420 Fix for OpenAPI Component Properties, Server Endpoint, and Path Filtering Issues
  examples/OpenApi-TuttiFrutti.ps1
  examples/PetStore/Petstore-OpenApiMultiTag.ps1
  src/Locales/ar/Pode.psd1
  src/Locales/de/Pode.psd1
  src/Locales/en-us/Pode.psd1
  src/Locales/en/Pode.psd1
  src/Locales/es/Pode.psd1
  src/Locales/fr/Pode.psd1
  src/Locales/it/Pode.psd1
  src/Locales/ja/Pode.psd1
  src/Locales/ko/Pode.psd1
  src/Locales/nl/Pode.psd1
  src/Locales/pl/Pode.psd1
  src/Locales/pt/Pode.psd1
  src/Locales/zh/Pode.psd1
  src/Private/OpenApi.ps1
  src/Public/OAProperties.ps1
  src/Public/OpenApi.ps1
  tests/integration/specs/OpenApi-TuttiFrutti_3.0.3.json
  tests/integration/specs/OpenApi-TuttiFrutti_3.1.0.json
  tests/unit/OpenApi.Tests.ps1
Labels: bug :bug:

#1427 Fixes "collection modified" error when cleaning up sessions
  src/Private/Sessions.ps1
Labels: bug :bug:

#1428 Migrates Stream functions into the .NET Listener
  src/Listener/PodeCompressionType.cs
  src/Listener/PodeHelpers.cs
  src/Private/Helpers.ps1
  src/Private/Streams.ps1
  src/Public/Responses.ps1
Labels: security :lock:

#1430 Fix OpenAPI Route parameters so they respect the DefinitionTag; Order Routes in OpenAPI specification by creation, and HTTP methods in a more conventional order; Add-PodeOAComponentRequestBody now supports hashtable/ordered input; More appropriately order responses, parameters, and request bodies in OpenAPI
  examples/OpenApi-TuttiFrutti.ps1
  examples/PetStore/Petstore-OpenApi.ps1
  examples/PetStore/Petstore-OpenApiMultiTag.ps1
  examples/PetStore/server.psd1
  src/Private/Context.ps1
  src/Private/OpenApi.ps1
  src/Public/OAComponents.ps1
  src/Public/OpenApi.ps1
  src/Public/Routes.ps1
  tests/integration/OpenApi.Tests.ps1
  tests/integration/specs/OpenApi-TuttiFrutti_3.0.3.json
  tests/integration/specs/OpenApi-TuttiFrutti_3.1.0.json
  tests/unit/OpenApi.Tests.ps1
Labels: bug :bug:

#1434 Fixes the clean-up of old log files
  src/Private/Logging.ps1
Labels: bug :bug:

#1436 Add -AllowNonStandardBody Parameter to Enable Request Bodies for Non-Standard HTTP Methods in OpenAPI
  src/Locales/ar/Pode.psd1
  src/Locales/de/Pode.psd1
  src/Locales/en-us/Pode.psd1
  src/Locales/en/Pode.psd1
  src/Locales/es/Pode.psd1
  src/Locales/fr/Pode.psd1
  src/Locales/it/Pode.psd1
  src/Locales/ja/Pode.psd1
  src/Locales/ko/Pode.psd1
  src/Locales/nl/Pode.psd1
  src/Locales/pl/Pode.psd1
  src/Locales/pt/Pode.psd1
  src/Locales/zh/Pode.psd1
  src/Public/OpenApi.ps1
  tests/unit/OpenApi.Tests.ps1
Labels: bug :bug:

#1438 Fixes the unnecessary Error Logging on HTTP Request Timeouts
  src/Listener/PodeContext.cs
  src/Listener/PodeRequest.cs
  src/Listener/PodeSocket.cs
Labels: bug :bug:

#1439 Don't setup the Caching Housekeeper Timer in a Serverless context
  src/Private/Caching.ps1
  src/Private/Server.ps1
Labels: bug :bug:
