Repository Badgerati/Pode, pull requests merged in 2025-03, with the labels that each got.

#1518 Improved Compatibility for `Write-PodeHostDivider` on Older Windows Versions
  src/Private/Console.ps1
Labels: enhancement :arrow_up:, story-points: 1

#1515 Fix: Prevent Early Invocation of Write-PodeErrorLog in Console Setup
  src/Private/Context.ps1
  src/Public/Core.ps1
Labels: bug :bug:, story-points: 1

#1507 Fixes the way logs are removed when using MaxDays, and servers restart daily; Fixes Pode removing more log files than expected due to too broad of a filter
  src/Private/Logging.ps1
Labels: bug :bug:, story-points: 1

#1495 Adds Hostname, Scheme, Query, and UtcDate to raw Request item for logging
  src/Private/Logging.ps1
Labels: story-points: 1, priority: low

#1524 Fixes AzureAD link in Authentication Overview page
  docs/Tutorials/Authentication/Overview.md
Labels: documentation :book:, story-points: 1
