Repository Badgerati/Pode, pull requests merged in 2025-04, with the labels that each got.

#1534 Fixes an issue with loading static content paths which contain wildcard characters
  examples/assets/[metadata].json
  examples/public/[brackets].txt
  src/Private/Helpers.ps1
  src/Private/Responses.ps1
  src/Private/Routes.ps1
  src/Public/Responses.ps1
  src/Public/Routes.ps1
  tests/unit/Helpers.Tests.ps1
Labels: bug :bug:

#1532 Fix buffer reuse issue in WebSockets
  docs/Tutorials/WebSockets/Endpoints.md
  src/Listener/PodeRequest.cs
  src/Listener/PodeServerSignal.cs
  src/Listener/PodeSignalRequest.cs
  tests/integration/WebSocket.Tests.ps1
Labels: bug :bug:

#1535 Adds new mapping for .mjs files, to application/javascript content-type
  src/Private/Mappers.ps1
  tests/unit/Mappers.Tests.ps1
Labels: enhancement :arrow_up:

#1536 Fix crash during server restart, by clearing existing limit rules
  src/Private/Server.ps1
  tests/unit/Server.Tests.ps1
Labels: bug :bug:

#1509 Support for Custom and default Favicons in Pode Endpoints
  docs/Tutorials/Endpoints/Favicon.md
  examples/PetStore/Petstore-OpenApi.ps1
  src/Misc/favicon.ico
  src/Pode.psd1
  src/Private/Helpers.ps1
  src/Private/Middleware.ps1
  src/Private/PodeServer.ps1
  src/Private/Responses.ps1
  src/Private/Serverless.ps1
  src/Public/Endpoint.ps1
  src/Public/FavIcon.ps1
  tests/unit/Favicon.Tests.ps1
Labels: enhancement :arrow_up:, story-points: 3

#1537 Adds support for fragmented WebSocket frames, and larger payloads
  src/Listener/PodeContext.cs
  src/Listener/PodeHelpers.cs
  src/Listener/PodeListener.cs
  src/Listener/PodeProtocol.cs
  src/Listener/PodeRequest.cs
  src/Listener/PodeResponse.cs
  src/Listener/PodeSignalFrame.cs
  src/Listener/PodeSignalRequest.cs
  src/Listener/PodeWsOpCode.cs
  src/Public/Responses.ps1
  tests/integration/WebSocket.Tests.ps1
Labels: enhancement :arrow_up:

#1539 Fixes a scoping issue in .pode files, where $_ would sometimes be $null
  src/Private/Helpers.ps1
Labels: bug :bug:

#1540 Re-use existing FileInfo objects for reading/writing byte streams; Removes redundant MemoryStream which doubled memory-use when writing to Responses
  docs/Tutorials/Endpoints/Favicon.md
  src/Listener/PodeResponse.cs
  src/Private/Helpers.ps1
  src/Private/Mappers.ps1
  src/Private/Middleware.ps1
  src/Private/PodeServer.ps1
  src/Private/Responses.ps1
  src/Private/Routes.ps1
  src/Private/Serverless.ps1
  src/Public/Responses.ps1
  src/Public/Routes.ps1
  tests/unit/Middleware.Tests.ps1
  tests/unit/Responses.Tests.ps1
Labels: performance :zap:

#1541 Bump MkDocs-Material theme to v9.6.12
  pode.build.ps1
Labels: packaging :package:

#1542 Fixes the file browser icons, so they render on PS5; Fixes the file browser parent directory create/update dates
  src/Misc/default-file-browsing.html.pode
  src/Private/Responses.ps1
  tests/unit/Responses.Tests.ps1
Labels: bug :bug:

#1546 Fixes unquoted YAML strings starting with special characters, incorrect indentation for standalone block literals, and incorrect line endings (CRLF)
  src/Private/Helpers.ps1
  tests/unit/Helpers.Tests.ps1
Labels: bug :bug:

#1538 Bundles the OpenAPI Documentation Libraries with the Pode Module, for stability and to support offline servers
  .github/dependabot.yml
  .gitignore
  docs/Getting-Started/build.md
  examples/OpenApi-TuttiFrutti.ps1
  licenses/LICENSE.Font-Awesome.txt
  licenses/LICENSE.RapiDoc.txt
  licenses/LICENSE.RapiPdf.txt
  licenses/LICENSE.bootstrap.txt
  licenses/LICENSE.highlightjs.txt
  licenses/LICENSE.openapi-explorer.txt
  licenses/LICENSE.redoc.txt
  licenses/LICENSE.stoplight.txt
  licenses/LICENSE.swagger-editor.txt
  licenses/LICENSE.swagger-ui.txt
  package.json
  pode.build.ps1
  src/Misc/default-doc-bookmarks.html.pode
  src/Misc/default-explorer.html.pode
  src/Misc/default-rapidoc.html.pode
  src/Misc/default-rapipdf.html.pode
  src/Misc/default-redoc.html.pode
  src/Misc/default-stoplight.html.pode
  src/Misc/default-swagger-editor.html.pode
  src/Misc/default-swagger.html.pode
  src/Public/OpenApi.ps1
  src/Public/Routes.ps1
Labels: enhancement :arrow_up:

#1549 Bumps the PS7.5 version in GitHub Actions to 7.5.1; Bumps the InvokeBuild version in GitHub Actions to 5.12.2
  .github/workflows/VirusTotal.yml
  .github/workflows/ci-coverage.yml
  .github/workflows/ci-docs.yml
  .github/workflows/ci-powershell.yml
  .github/workflows/ci-pwsh7_5.yml
  .github/workflows/ci-pwsh_lts.yml
  .github/workflows/ci-pwsh_preview.yml
Labels: packaging :package:

#1552 Adds Releases Notes for v2.12.1
  docs/release-notes.md
  pode.build.ps1
Labels: exclude-from-release-notes
