Repository Badgerati/Pode, pull requests merged in 2025-02, with the labels that each got.

#1478 Fixes for `Suspend-PodeServer`, `Resume-PodeServer`, and Endpoint Data Handling
  src/Private/CancellationToken.ps1
  src/Private/Console.ps1
  src/Private/Server.ps1
  src/Public/Core.ps1
Labels: bug :bug:

#1469 Improved Access and Rate Limiting Middleware
  docs/Tutorials/Middleware/Overview.md
  docs/Tutorials/Middleware/Types/AccessRules.md
  docs/Tutorials/Middleware/Types/Limiters/AccessRules.md
  docs/Tutorials/Middleware/Types/Limiters/Components.md
  docs/Tutorials/Middleware/Types/Limiters/RateRules.md
  docs/Tutorials/Middleware/Types/RateLimiting.md
  docs/Tutorials/Server Operations/Overview.md
  examples/Mail-Server.ps1
  examples/Tcp-ServerHttp.ps1
  examples/Web-Pages.ps1
  examples/server.psd1
  src/Locales/ar/Pode.psd1
  src/Locales/de/Pode.psd1
  src/Locales/en-us/Pode.psd1
  src/Locales/en/Pode.psd1
  src/Locales/es/Pode.psd1
  src/Locales/fr/Pode.psd1
  src/Locales/it/Pode.psd1
  src/Locales/ja/Pode.psd1
  src/Locales/ko/Pode.psd1
  src/Locales/nl/Pode.psd1
  src/Locales/pl/Pode.psd1
  src/Locales/pt/Pode.psd1
  src/Locales/zh/Pode.psd1
  src/Pode.psd1
  src/Private/Context.ps1
  src/Private/Helpers.ps1
  src/Private/Limit.ps1
  src/Private/Middleware.ps1
  src/Private/Responses.ps1
  src/Private/Security.ps1
  src/Private/Server.ps1
  src/Private/SmtpServer.ps1
  src/Private/TcpServer.ps1
  src/Public/Limit.ps1
  src/Public/Middleware.ps1
  src/Public/Responses.ps1
  tests/unit/Context.Tests.ps1
  tests/unit/Helpers.Tests.ps1
  tests/unit/Middleware.Tests.ps1
  tests/unit/Security.Tests.ps1
Labels: enhancement :arrow_up:

#1482 Fix for how the content-transfer-encoding SMTP header is extracted
  src/Listener/PodeSmtpRequest.cs
Labels: bug :bug:

#1483 Set initial runspace location to be the Server Root path
  src/Private/Runspaces.ps1
  src/Private/Timers.ps1
Labels: bug :bug:

#1484 Add documentation for the various Route response type functions
  docs/Tutorials/Routes/Utilities/ErrorPages.md
  docs/Tutorials/Routes/Utilities/ResponseTypes.md
  src/Private/Responses.ps1
  src/Public/Responses.ps1
Labels: documentation :book:

#1486 Bumps PowerShell in Dockerfiles to v7.5
  .github/workflows/ci-pwsh7_5.yml
  Dockerfile
  alpine.dockerfile
  arm32.dockerfile
  docs/Getting-Started/Installation.md
  docs/Hosting/Docker.md
Labels: packaging :package:

#1487 Adds support for retrying failed Task processes
  docs/Tutorials/Tasks.md
  examples/Tasks.ps1
  src/Pode.psd1
  src/Private/Tasks.ps1
  src/Public/Tasks.ps1
Labels: enhancement :arrow_up:

#1488 Adds support for retrieving the IP address from the X-Forwarded-For header, for Access/Rate Limit rules
  docs/Hosting/IIS.md
  docs/Tutorials/Middleware/Types/Limiters/Components.md
  examples/IIS-Example.ps1
  examples/web.config
  src/Private/Helpers.ps1
  src/Public/Limit.ps1
Labels: enhancement :arrow_up:

#1489 Bumps Pester to v5.7.1
  pode.build.ps1
Labels: packaging :package:

#1490 Bump MkDocs-Material theme to v9.6.4
  mkdocs.yml
  pode.build.ps1
Labels: packaging :package:

#1496 Ensure Consistent Enum Key Usage for Pode Events
  src/Private/Events.ps1
  src/Public/Events.ps1
Labels: bug :bug:

#1460 Fixes ObjectDisposedException in during SSL/TLS operations
  examples/Web-SelfSigned.ps1
  src/Listener/PodeHttpRequest.cs
  src/Listener/PodeRequest.cs
  src/Listener/PodeSignalRequest.cs
  src/Listener/PodeSmtpRequest.cs
  src/Listener/PodeTcpRequest.cs
Labels: bug :bug:

#1498 v2.12.0 Prep
  docs/release-notes.md
  pode.build.ps1
Labels: exclude-from-release-notes
